# Site settings
baseURL = "https://ashy-forest-07c501103.2.azurestaticapps.net"
languageCode = "sv-SE"
title = "Split - HTML Template Demo"
theme = "Skeppström Konsult"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]

# Local preview mode
relativeURLs = true
uglyURLs = true

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Copyright
copyright = "&copy;2021 Your Name"

[params]

  # Metadata for search engines and social sharing
  author = "Jenny Jones"
  description = "Split is a centrally-divided layout for a professional online presence with a big image or video left with alongside content."
  shareImage = "images/social.jpg"
  twitterHandle = "onepagelove"

  # Favicon
  favicon = "favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "skeper.png"
      position = "center center"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/background.mp4"
      # youtubeId = "dk9uNWPP7EA"

  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Kontakt"

      [[params.links.list1.link]]
        text = "070 854 24 45"
        url = "tel:+46708542445"
        new_tab = true # new tab

      [[params.links.list1.link]]
        text = "pernilla@skeppstromkonsult.se"
        url = "mailto://pernilla@skeppstromkonsult.se"
        new_tab = false # Default, open at same tab

      [[params.links.list1.link]]
        text = ""
        url = ""

  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = ""

      [[params.links.list2.link]]
        text = ""
        url = ""

      [[params.links.list2.link]]
        text = ""
        url = ""

      [[params.links.list2.link]]
        text = ""
        url = ""

  # Links List #3
  [[params.links]]
    [params.links.list3]
      heading = "Länkar"

      [[params.links.list3.link]]
        text = "LinkedIn"
        url = "https://www.linkedin.com/in/pernilla-skeppstr%C3%B6m-16b80548"

      [[params.links.list3.link]]
        text = "Instagram"
        url = "https://www.instagram.com/skeppstromkonsult.se/"

      [[params.links.list3.link]]
        text = "Facebook"
        url = "https://www.facebook.com/skeppstromkonsult.se"

  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split
